### ISSUE TITLE
Extend the Karplus-Strong model

### ISSUE THREAD

**Issue by cwellm** [bynarlogic/string-vst#2]
**Description**

As a synthesizer developer, I want to get a feeling about the implementation of the Karplus-Strong algorithm in the RNBO framework.

**Acceptance Criteria**

- [ ] extend the algorithm
  - [ ] in RNBO
  - [ ] 1-2 more user controllable parameters
  - [ ] export to working C++ code

**Comment by bynarlogic** [comment]
Looks great! Let me know if you want to pair in Max.
